# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: sample echo
        run: |
          echo "------------- Contents of sample.txt ----------------"
          cat sample.txt
          echo "------------- Content End ---------------------------"
  # This workflow contains a single job called "build"
  code-coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    timeout-minutes: 120

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set up lcov
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install lcov
          cpan -i Date::Parse
          lcov --version
          genhtml --version

      - name: Using genhtml
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          genhtml --version

      - name: Upload Dummy XML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml-report
          path: some-report.xml
          retention-days: 1
          if-no-files-found: ignore
          
